### ISSUE TITLE
Can you teach me how to convert EEG files to HDF5 files?

### ISSUE THREAD

**Issue by NormanGod** [deepBrains/TSception#3]
Can you teach me how to convert EEG files to HDF5 files,Thanks.

**Comment by deepBrains** [comment]
Hi, thanks for your interest. HDF5 files just a format to save the data, you can also use .MAT, .NPY and so on. What you need to do is to load your original EEG data, do the pre-processing( band-pass, EOG removal, etc.) and change the processed data into (trials x channels x data points) format, and save it in any form you like.  Then you can load the saved data(trials x channels x data points) using the corresponding function( e.g.  h5py.File() for HDF5 files, scipy.io.loadmat() for .MAT) to do the next process. Hope it can help.
