### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Brainxwq** [deepBrains/TSception#4]
Hello, thank you very much for your sharing. And where can I download the complete dataset?

**Comment by deepBrains** [comment]
Thanks for your interest, but I am sorry the data is not yet considered to be publicly accessed due to the ethics approval.

**Comment by Brainxwq** [comment]
I would like to quote your paper. Could you please share the data set and make a comparison?I am absolutely subject to the ethical point of view！Thank you very much
